### ISSUE TITLE
TODO pre RTB 

### ISSUE THREAD

**Issue by mzecchinato** [Argo-swe/Docs#168]
- [x] aggiornare versioni doc su global
- [x] compilare tutti i doc (anche verbali ci sono fix sparse)
- [x] ricontrollare utilizzo comandi di ruolo
- [x]  sviluppatore lo cambiamo in programmatore? non ci sono troppe occorrenze e userei il comando se confermiamo
- [x] ...

**Comment by stoccotommaso02** [comment]
>     * [ ]  compilare tutti i doc (anche verbali ci sono fix sparse)
> 
Cosa intendi? L'action che parte al merge con main già in automatico compila tutta la directory RTB e la clona nel github.io

**Comment by stoccotommaso02** [comment]
>     * [ ]  ricontrollare utilizzo comandi di ruolo
> 
Me ne occupo domattina, per chiarezza si tratta di due cose:
- Aggiungere delimitatori del comando (graffe vuote) quando necessario
- Controllare che nel documento siano capitalizzati (o non capitalizzati) come previsto

**Comment by mzecchinato** [comment]
replico qui il messaggio di telegram così lo vedono tutti, come gestire i comandi di ruolo con maiuscole e minuscole
```
\Responsabile[U]{} con maiuscola
\Responsabile{} con minuscola
```

**Comment by mzecchinato** [comment]
dovrebbero essere tutti OK, ma meglio darci un'occhiata
PS. mancano però tutti i termini non gestiti con i comandi (parole amminstratore, ecc sparse in giro)

**Comment by Rikicavaz77** [comment]
> PS. mancano però tutti i termini non gestiti con i comandi (parole amminstratore, ecc sparse in giro

Nei verbali o nel PdP ormai lascerei senza comandi, tanto non dovrebbe dare problemi.

**Comment by Rikicavaz77** [comment]
Per il resto ne discutiamo post-RTB.
